version: '3.8'
services:
  app-server:
    build: .

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=aslamjm
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-db:/data/db  

volumes:
  mongo-db:        